//go:build ignore
// +build ignore

// This program generates named_sequences_data.go from NamedSequences.txt.
// Run with: go run generate_named_sequences.go
//
// NamedSequences-17.0.0.txt format (after stripping '#' comments):
//
//	KEYCAP NUMBER SIGN;0023 FE0F 20E3
//	LATIN SMALL LETTER A WITH MACRON AND GRAVE;0101 0300
//
// Field 0: the name of the sequence (A-Z, 0-9, space, hyphen).
// Field 1: the code point sequence (two or more space-separated hex values).
//
// Only the normative NamedSequences.txt is processed. The provisional file
// NamedSequencesProv.txt is intentionally ignored, per UAX #34.
//
// Reference: https://www.unicode.org/reports/tr34/
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
)

const (
	namedSequencesURL     = "https://www.unicode.org/Public/17.0.0/ucd/NamedSequences.txt"
	namedSequencesVersion = "17.0.0"
)

type namedSequence struct {
	name string
	seq  []rune
}

func main() {
	fmt.Println("Downloading Unicode NamedSequences data file...")

	entries, err := downloadAndParse(namedSequencesURL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing NamedSequences.txt: %v\n", err)
		os.Exit(1)
	}

	// Sort by name for deterministic, binary-searchable output. Names are
	// unique in NamedSequences.txt, so name order is a total order.
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].name < entries[j].name
	})

	fmt.Printf("Parsed %d named character sequences\n", len(entries))

	if err := generateCode(entries); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating code: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Successfully generated named_sequences_data.go")
}

func downloadAndParse(url string) ([]namedSequence, error) {
	resp, err := http.Get(url)
	if err != nil {
		return nil, fmt.Errorf("download: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("download: status %d", resp.StatusCode)
	}
	return parse(resp.Body)
}

func parse(r io.Reader) ([]namedSequence, error) {
	var entries []namedSequence
	seenName := make(map[string]bool)
	seenSeq := make(map[string]string) // sequence key -> first name, for verification

	scanner := bufio.NewScanner(r)
	lineNum := 0
	for scanner.Scan() {
		lineNum++
		raw := scanner.Text()
		// Strip comments beginning with '#'.
		if hash := strings.IndexByte(raw, '#'); hash >= 0 {
			raw = raw[:hash]
		}
		line := strings.TrimSpace(raw)
		if line == "" {
			continue
		}

		parts := strings.Split(line, ";")
		if len(parts) < 2 {
			continue
		}

		name := strings.TrimSpace(parts[0])
		fields := strings.Fields(parts[1])
		if name == "" || len(fields) < 2 {
			// Named sequences are, by definition, two or more code points.
			log.Fatalf("line %d: malformed entry %q (need a name and >=2 code points)", lineNum, line)
		}

		seq := make([]rune, 0, len(fields))
		for _, f := range fields {
			v, err := strconv.ParseInt(f, 16, 32)
			if err != nil {
				log.Fatalf("line %d: bad code point %q: %v", lineNum, f, err)
			}
			seq = append(seq, rune(v))
		}

		// Names are the unique key of the file. Fail loudly if that ever changes.
		if seenName[name] {
			log.Fatalf("line %d: duplicate name %q — generator assumes unique names", lineNum, name)
		}
		seenName[name] = true

		// Verify the (sequence -> name) mapping is a bijection so reverse
		// lookup is well defined. Fail loudly if a sequence is ever reused.
		key := string(seq)
		if prev, ok := seenSeq[key]; ok {
			log.Fatalf("line %d: sequence for %q also names %q — reverse lookup would be ambiguous", lineNum, name, prev)
		}
		seenSeq[key] = name

		entries = append(entries, namedSequence{name: name, seq: seq})
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return entries, nil
}

func generateCode(entries []namedSequence) error {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by generate_named_sequences.go. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "// Source: Unicode NamedSequences-%s.txt\n", namedSequencesVersion)
	fmt.Fprintf(&buf, "\npackage uax34\n\n")

	fmt.Fprintf(&buf, "// namedSequence pairs a Named Character Sequence name with its\n")
	fmt.Fprintf(&buf, "// code point sequence (two or more code points).\n")
	fmt.Fprintf(&buf, "type namedSequence struct {\n")
	fmt.Fprintf(&buf, "\tname string\n")
	fmt.Fprintf(&buf, "\tseq  []rune\n")
	fmt.Fprintf(&buf, "}\n\n")

	fmt.Fprintf(&buf, "// namedSequenceData lists every normative Named Character Sequence from\n")
	fmt.Fprintf(&buf, "// NamedSequences.txt, sorted ascending by name so the table supports\n")
	fmt.Fprintf(&buf, "// binary search and yields deterministic output. Names are unique and\n")
	fmt.Fprintf(&buf, "// each sequence maps to exactly one name (a bijection).\n")
	fmt.Fprintf(&buf, "// Total entries: %d\n", len(entries))
	fmt.Fprintf(&buf, "var namedSequenceData = []namedSequence{\n")
	for _, e := range entries {
		fmt.Fprintf(&buf, "\t{%q, []rune{", e.name)
		for i, r := range e.seq {
			if i > 0 {
				fmt.Fprintf(&buf, ", ")
			}
			fmt.Fprintf(&buf, "0x%04X", r)
		}
		fmt.Fprintf(&buf, "}},\n")
	}
	fmt.Fprintf(&buf, "}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w", err)
	}

	return os.WriteFile("named_sequences_data.go", src, 0o644)
}
