//go:build ignore
// +build ignore

// This program generates casefold_data.go from Unicode CaseFolding.txt.
// Run with: go run generate_casefold.go
//
// UTS #39 specifies "full case folding" for the skeleton algorithm, which
// corresponds to including the status 'C' (common) and 'F' (full) mappings
// from CaseFolding.txt and skipping 'S' (simple) and 'T' (Turkic) mappings.
//
// See: https://www.unicode.org/reports/tr39/#Confusable_Detection
//      https://www.unicode.org/Public/17.0.0/ucd/CaseFolding.txt

package main

import (
	"bufio"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
)

const (
	caseFoldingURL = "https://www.unicode.org/Public/17.0.0/ucd/CaseFolding.txt"
	unicodeVersion = "17.0.0"
)

type caseFoldMapping struct {
	source rune
	target string // May be multiple runes (full folding)
	status string // C or F
}

func main() {
	fmt.Println("Downloading CaseFolding.txt...")
	resp, err := http.Get(caseFoldingURL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error downloading CaseFolding.txt: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		fmt.Fprintf(os.Stderr, "Error: HTTP %d\n", resp.StatusCode)
		os.Exit(1)
	}

	mappings := parseCaseFolding(resp.Body)
	fmt.Printf("Parsed %d C+F case fold mappings\n", len(mappings))

	if err := generateCaseFoldFile(mappings); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing casefold_data.go: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated casefold_data.go")
}

func parseCaseFolding(r io.Reader) []caseFoldMapping {
	scanner := bufio.NewScanner(r)
	var mappings []caseFoldMapping

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip comments and empty lines.
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Strip inline comments.
		if idx := strings.Index(line, "#"); idx >= 0 {
			line = strings.TrimSpace(line[:idx])
		}

		// Format: <code>; <status>; <mapping>;
		parts := strings.Split(line, ";")
		if len(parts) < 3 {
			continue
		}

		sourceStr := strings.TrimSpace(parts[0])
		status := strings.TrimSpace(parts[1])
		targetStr := strings.TrimSpace(parts[2])

		// UTS #39 calls for "full case folding": include C (common) and F (full)
		// mappings; exclude S (simple) and T (Turkic).
		if status != "C" && status != "F" {
			continue
		}

		sourceVal, err := strconv.ParseInt(sourceStr, 16, 32)
		if err != nil {
			continue
		}

		targetRunes := parseCodePoints(targetStr)
		if len(targetRunes) == 0 {
			continue
		}

		mappings = append(mappings, caseFoldMapping{
			source: rune(sourceVal),
			target: string(targetRunes),
			status: status,
		})
	}

	// Sort by source code point for binary search.
	sort.Slice(mappings, func(i, j int) bool {
		return mappings[i].source < mappings[j].source
	})

	return mappings
}

func parseCodePoints(s string) []rune {
	parts := strings.Fields(s)
	runes := make([]rune, 0, len(parts))

	for _, part := range parts {
		val, err := strconv.ParseInt(part, 16, 32)
		if err != nil {
			continue
		}
		runes = append(runes, rune(val))
	}

	return runes
}

func generateCaseFoldFile(mappings []caseFoldMapping) error {
	f, err := os.Create("casefold_data.go")
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintf(f, "// Code generated by generate_casefold.go. DO NOT EDIT.\n")
	fmt.Fprintf(f, "// Source: %s\n", caseFoldingURL)
	fmt.Fprintf(f, "// Unicode version: %s\n", unicodeVersion)
	fmt.Fprintf(f, "// Includes status C (common) and F (full) mappings only,\n")
	fmt.Fprintf(f, "// per UTS #39's \"full case folding\" requirement.\n")
	fmt.Fprintf(f, "\npackage uts39\n\n")

	fmt.Fprintf(f, "// caseFoldEntry represents a case folding mapping from a single\n")
	fmt.Fprintf(f, "// source code point to (possibly multiple) target code points.\n")
	fmt.Fprintf(f, "type caseFoldEntry struct {\n")
	fmt.Fprintf(f, "\tsource rune\n")
	fmt.Fprintf(f, "\ttarget string\n")
	fmt.Fprintf(f, "}\n\n")
	// The remaining output is run through gofmt by the caller; this generator
	// emits canonical tab-indented Go source.

	fmt.Fprintf(f, "// caseFoldData contains the full case folding mappings (C + F)\n")
	fmt.Fprintf(f, "// from CaseFolding.txt. Sorted by source for binary search.\n")
	fmt.Fprintf(f, "var caseFoldData = []caseFoldEntry{\n")

	for _, m := range mappings {
		fmt.Fprintf(f, "\t{0x%04X, %s}, // (%s)\n",
			m.source, fmt.Sprintf("%+q", m.target), m.status)
	}

	fmt.Fprintf(f, "}\n")
	return nil
}
