// Code generated by generate_brackets.go. DO NOT EDIT.
// Source: Unicode BidiBrackets-17.0.0.txt

package uax9

// bracketPairType encodes the Bidi_Paired_Bracket_Type property.
// Reference: https://www.unicode.org/reports/tr9/#BD16
type bracketPairType uint8

const (
	bracketNone  bracketPairType = 0
	bracketOpen  bracketPairType = 1
	bracketClose bracketPairType = 2
)

// bracketEntry captures one row of BidiBrackets.txt.
type bracketEntry struct {
	r      rune
	paired rune
	ptype  bracketPairType
}

// bracketData lists every code point with Bidi_Paired_Bracket_Type ∈ {Open, Close},
// sorted ascending by code point for binary search.
// Total entries: 128
var bracketData = []bracketEntry{
	{0x0028, 0x0029, bracketOpen},  // LEFT PARENTHESIS
	{0x0029, 0x0028, bracketClose}, // RIGHT PARENTHESIS
	{0x005B, 0x005D, bracketOpen},  // LEFT SQUARE BRACKET
	{0x005D, 0x005B, bracketClose}, // RIGHT SQUARE BRACKET
	{0x007B, 0x007D, bracketOpen},  // LEFT CURLY BRACKET
	{0x007D, 0x007B, bracketClose}, // RIGHT CURLY BRACKET
	{0x0F3A, 0x0F3B, bracketOpen},  // TIBETAN MARK GUG RTAGS GYON
	{0x0F3B, 0x0F3A, bracketClose}, // TIBETAN MARK GUG RTAGS GYAS
	{0x0F3C, 0x0F3D, bracketOpen},  // TIBETAN MARK ANG KHANG GYON
	{0x0F3D, 0x0F3C, bracketClose}, // TIBETAN MARK ANG KHANG GYAS
	{0x169B, 0x169C, bracketOpen},  // OGHAM FEATHER MARK
	{0x169C, 0x169B, bracketClose}, // OGHAM REVERSED FEATHER MARK
	{0x2045, 0x2046, bracketOpen},  // LEFT SQUARE BRACKET WITH QUILL
	{0x2046, 0x2045, bracketClose}, // RIGHT SQUARE BRACKET WITH QUILL
	{0x207D, 0x207E, bracketOpen},  // SUPERSCRIPT LEFT PARENTHESIS
	{0x207E, 0x207D, bracketClose}, // SUPERSCRIPT RIGHT PARENTHESIS
	{0x208D, 0x208E, bracketOpen},  // SUBSCRIPT LEFT PARENTHESIS
	{0x208E, 0x208D, bracketClose}, // SUBSCRIPT RIGHT PARENTHESIS
	{0x2308, 0x2309, bracketOpen},  // LEFT CEILING
	{0x2309, 0x2308, bracketClose}, // RIGHT CEILING
	{0x230A, 0x230B, bracketOpen},  // LEFT FLOOR
	{0x230B, 0x230A, bracketClose}, // RIGHT FLOOR
	{0x2329, 0x232A, bracketOpen},  // LEFT-POINTING ANGLE BRACKET
	{0x232A, 0x2329, bracketClose}, // RIGHT-POINTING ANGLE BRACKET
	{0x2768, 0x2769, bracketOpen},  // MEDIUM LEFT PARENTHESIS ORNAMENT
	{0x2769, 0x2768, bracketClose}, // MEDIUM RIGHT PARENTHESIS ORNAMENT
	{0x276A, 0x276B, bracketOpen},  // MEDIUM FLATTENED LEFT PARENTHESIS ORNAMENT
	{0x276B, 0x276A, bracketClose}, // MEDIUM FLATTENED RIGHT PARENTHESIS ORNAMENT
	{0x276C, 0x276D, bracketOpen},  // MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT
	{0x276D, 0x276C, bracketClose}, // MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT
	{0x276E, 0x276F, bracketOpen},  // HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT
	{0x276F, 0x276E, bracketClose}, // HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT
	{0x2770, 0x2771, bracketOpen},  // HEAVY LEFT-POINTING ANGLE BRACKET ORNAMENT
	{0x2771, 0x2770, bracketClose}, // HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT
	{0x2772, 0x2773, bracketOpen},  // LIGHT LEFT TORTOISE SHELL BRACKET ORNAMENT
	{0x2773, 0x2772, bracketClose}, // LIGHT RIGHT TORTOISE SHELL BRACKET ORNAMENT
	{0x2774, 0x2775, bracketOpen},  // MEDIUM LEFT CURLY BRACKET ORNAMENT
	{0x2775, 0x2774, bracketClose}, // MEDIUM RIGHT CURLY BRACKET ORNAMENT
	{0x27C5, 0x27C6, bracketOpen},  // LEFT S-SHAPED BAG DELIMITER
	{0x27C6, 0x27C5, bracketClose}, // RIGHT S-SHAPED BAG DELIMITER
	{0x27E6, 0x27E7, bracketOpen},  // MATHEMATICAL LEFT WHITE SQUARE BRACKET
	{0x27E7, 0x27E6, bracketClose}, // MATHEMATICAL RIGHT WHITE SQUARE BRACKET
	{0x27E8, 0x27E9, bracketOpen},  // MATHEMATICAL LEFT ANGLE BRACKET
	{0x27E9, 0x27E8, bracketClose}, // MATHEMATICAL RIGHT ANGLE BRACKET
	{0x27EA, 0x27EB, bracketOpen},  // MATHEMATICAL LEFT DOUBLE ANGLE BRACKET
	{0x27EB, 0x27EA, bracketClose}, // MATHEMATICAL RIGHT DOUBLE ANGLE BRACKET
	{0x27EC, 0x27ED, bracketOpen},  // MATHEMATICAL LEFT WHITE TORTOISE SHELL BRACKET
	{0x27ED, 0x27EC, bracketClose}, // MATHEMATICAL RIGHT WHITE TORTOISE SHELL BRACKET
	{0x27EE, 0x27EF, bracketOpen},  // MATHEMATICAL LEFT FLATTENED PARENTHESIS
	{0x27EF, 0x27EE, bracketClose}, // MATHEMATICAL RIGHT FLATTENED PARENTHESIS
	{0x2983, 0x2984, bracketOpen},  // LEFT WHITE CURLY BRACKET
	{0x2984, 0x2983, bracketClose}, // RIGHT WHITE CURLY BRACKET
	{0x2985, 0x2986, bracketOpen},  // LEFT WHITE PARENTHESIS
	{0x2986, 0x2985, bracketClose}, // RIGHT WHITE PARENTHESIS
	{0x2987, 0x2988, bracketOpen},  // Z NOTATION LEFT IMAGE BRACKET
	{0x2988, 0x2987, bracketClose}, // Z NOTATION RIGHT IMAGE BRACKET
	{0x2989, 0x298A, bracketOpen},  // Z NOTATION LEFT BINDING BRACKET
	{0x298A, 0x2989, bracketClose}, // Z NOTATION RIGHT BINDING BRACKET
	{0x298B, 0x298C, bracketOpen},  // LEFT SQUARE BRACKET WITH UNDERBAR
	{0x298C, 0x298B, bracketClose}, // RIGHT SQUARE BRACKET WITH UNDERBAR
	{0x298D, 0x2990, bracketOpen},  // LEFT SQUARE BRACKET WITH TICK IN TOP CORNER
	{0x298E, 0x298F, bracketClose}, // RIGHT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
	{0x298F, 0x298E, bracketOpen},  // LEFT SQUARE BRACKET WITH TICK IN BOTTOM CORNER
	{0x2990, 0x298D, bracketClose}, // RIGHT SQUARE BRACKET WITH TICK IN TOP CORNER
	{0x2991, 0x2992, bracketOpen},  // LEFT ANGLE BRACKET WITH DOT
	{0x2992, 0x2991, bracketClose}, // RIGHT ANGLE BRACKET WITH DOT
	{0x2993, 0x2994, bracketOpen},  // LEFT ARC LESS-THAN BRACKET
	{0x2994, 0x2993, bracketClose}, // RIGHT ARC GREATER-THAN BRACKET
	{0x2995, 0x2996, bracketOpen},  // DOUBLE LEFT ARC GREATER-THAN BRACKET
	{0x2996, 0x2995, bracketClose}, // DOUBLE RIGHT ARC LESS-THAN BRACKET
	{0x2997, 0x2998, bracketOpen},  // LEFT BLACK TORTOISE SHELL BRACKET
	{0x2998, 0x2997, bracketClose}, // RIGHT BLACK TORTOISE SHELL BRACKET
	{0x29D8, 0x29D9, bracketOpen},  // LEFT WIGGLY FENCE
	{0x29D9, 0x29D8, bracketClose}, // RIGHT WIGGLY FENCE
	{0x29DA, 0x29DB, bracketOpen},  // LEFT DOUBLE WIGGLY FENCE
	{0x29DB, 0x29DA, bracketClose}, // RIGHT DOUBLE WIGGLY FENCE
	{0x29FC, 0x29FD, bracketOpen},  // LEFT-POINTING CURVED ANGLE BRACKET
	{0x29FD, 0x29FC, bracketClose}, // RIGHT-POINTING CURVED ANGLE BRACKET
	{0x2E22, 0x2E23, bracketOpen},  // TOP LEFT HALF BRACKET
	{0x2E23, 0x2E22, bracketClose}, // TOP RIGHT HALF BRACKET
	{0x2E24, 0x2E25, bracketOpen},  // BOTTOM LEFT HALF BRACKET
	{0x2E25, 0x2E24, bracketClose}, // BOTTOM RIGHT HALF BRACKET
	{0x2E26, 0x2E27, bracketOpen},  // LEFT SIDEWAYS U BRACKET
	{0x2E27, 0x2E26, bracketClose}, // RIGHT SIDEWAYS U BRACKET
	{0x2E28, 0x2E29, bracketOpen},  // LEFT DOUBLE PARENTHESIS
	{0x2E29, 0x2E28, bracketClose}, // RIGHT DOUBLE PARENTHESIS
	{0x2E55, 0x2E56, bracketOpen},  // LEFT SQUARE BRACKET WITH STROKE
	{0x2E56, 0x2E55, bracketClose}, // RIGHT SQUARE BRACKET WITH STROKE
	{0x2E57, 0x2E58, bracketOpen},  // LEFT SQUARE BRACKET WITH DOUBLE STROKE
	{0x2E58, 0x2E57, bracketClose}, // RIGHT SQUARE BRACKET WITH DOUBLE STROKE
	{0x2E59, 0x2E5A, bracketOpen},  // TOP HALF LEFT PARENTHESIS
	{0x2E5A, 0x2E59, bracketClose}, // TOP HALF RIGHT PARENTHESIS
	{0x2E5B, 0x2E5C, bracketOpen},  // BOTTOM HALF LEFT PARENTHESIS
	{0x2E5C, 0x2E5B, bracketClose}, // BOTTOM HALF RIGHT PARENTHESIS
	{0x3008, 0x3009, bracketOpen},  // LEFT ANGLE BRACKET
	{0x3009, 0x3008, bracketClose}, // RIGHT ANGLE BRACKET
	{0x300A, 0x300B, bracketOpen},  // LEFT DOUBLE ANGLE BRACKET
	{0x300B, 0x300A, bracketClose}, // RIGHT DOUBLE ANGLE BRACKET
	{0x300C, 0x300D, bracketOpen},  // LEFT CORNER BRACKET
	{0x300D, 0x300C, bracketClose}, // RIGHT CORNER BRACKET
	{0x300E, 0x300F, bracketOpen},  // LEFT WHITE CORNER BRACKET
	{0x300F, 0x300E, bracketClose}, // RIGHT WHITE CORNER BRACKET
	{0x3010, 0x3011, bracketOpen},  // LEFT BLACK LENTICULAR BRACKET
	{0x3011, 0x3010, bracketClose}, // RIGHT BLACK LENTICULAR BRACKET
	{0x3014, 0x3015, bracketOpen},  // LEFT TORTOISE SHELL BRACKET
	{0x3015, 0x3014, bracketClose}, // RIGHT TORTOISE SHELL BRACKET
	{0x3016, 0x3017, bracketOpen},  // LEFT WHITE LENTICULAR BRACKET
	{0x3017, 0x3016, bracketClose}, // RIGHT WHITE LENTICULAR BRACKET
	{0x3018, 0x3019, bracketOpen},  // LEFT WHITE TORTOISE SHELL BRACKET
	{0x3019, 0x3018, bracketClose}, // RIGHT WHITE TORTOISE SHELL BRACKET
	{0x301A, 0x301B, bracketOpen},  // LEFT WHITE SQUARE BRACKET
	{0x301B, 0x301A, bracketClose}, // RIGHT WHITE SQUARE BRACKET
	{0xFE59, 0xFE5A, bracketOpen},  // SMALL LEFT PARENTHESIS
	{0xFE5A, 0xFE59, bracketClose}, // SMALL RIGHT PARENTHESIS
	{0xFE5B, 0xFE5C, bracketOpen},  // SMALL LEFT CURLY BRACKET
	{0xFE5C, 0xFE5B, bracketClose}, // SMALL RIGHT CURLY BRACKET
	{0xFE5D, 0xFE5E, bracketOpen},  // SMALL LEFT TORTOISE SHELL BRACKET
	{0xFE5E, 0xFE5D, bracketClose}, // SMALL RIGHT TORTOISE SHELL BRACKET
	{0xFF08, 0xFF09, bracketOpen},  // FULLWIDTH LEFT PARENTHESIS
	{0xFF09, 0xFF08, bracketClose}, // FULLWIDTH RIGHT PARENTHESIS
	{0xFF3B, 0xFF3D, bracketOpen},  // FULLWIDTH LEFT SQUARE BRACKET
	{0xFF3D, 0xFF3B, bracketClose}, // FULLWIDTH RIGHT SQUARE BRACKET
	{0xFF5B, 0xFF5D, bracketOpen},  // FULLWIDTH LEFT CURLY BRACKET
	{0xFF5D, 0xFF5B, bracketClose}, // FULLWIDTH RIGHT CURLY BRACKET
	{0xFF5F, 0xFF60, bracketOpen},  // FULLWIDTH LEFT WHITE PARENTHESIS
	{0xFF60, 0xFF5F, bracketClose}, // FULLWIDTH RIGHT WHITE PARENTHESIS
	{0xFF62, 0xFF63, bracketOpen},  // HALFWIDTH LEFT CORNER BRACKET
	{0xFF63, 0xFF62, bracketClose}, // HALFWIDTH RIGHT CORNER BRACKET
}

// getBracketInfo returns (type, paired-bracket) for the given rune.
// For non-bracket characters, returns (bracketNone, 0).
// Reference: https://www.unicode.org/reports/tr9/#BD16
func getBracketInfo(r rune) (bracketPairType, rune) {
	lo, hi := 0, len(bracketData)-1
	for lo <= hi {
		mid := (lo + hi) / 2
		entry := bracketData[mid]
		switch {
		case r < entry.r:
			hi = mid - 1
		case r > entry.r:
			lo = mid + 1
		default:
			return entry.ptype, entry.paired
		}
	}
	return bracketNone, 0
}

// canonicalBracket maps canonically-equivalent bracket characters
// to a single representative so BD16 matching is correct.
// U+2329 ≡ U+3008 and U+232A ≡ U+3009 per Unicode canonical equivalence.
// Reference: https://www.unicode.org/reports/tr9/#BD16
func canonicalBracket(r rune) rune {
	switch r {
	case 0x2329:
		return 0x3008
	case 0x232A:
		return 0x3009
	}
	return r
}
