//go:build ignore
// +build ignore

// This program generates brackets_data.go from BidiBrackets.txt.
// Run with: go run generate_brackets.go
//
// BidiBrackets-17.0.0.txt format:
//
//	0028; 0029; o # LEFT PARENTHESIS
//	0029; 0028; c # RIGHT PARENTHESIS
//
// Field 0: the bracket code point.
// Field 1: the Bidi_Paired_Bracket value — the matching mate.
// Field 2: the Bidi_Paired_Bracket_Type — "o" (Open) or "c" (Close).
//
// Reference: https://www.unicode.org/reports/tr9/#BD16
package main

import (
	"bufio"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
)

const (
	bracketsURL     = "https://www.unicode.org/Public/17.0.0/ucd/BidiBrackets.txt"
	bracketsVersion = "17.0.0"
)

type bracketEntry struct {
	r       rune
	paired  rune
	ptype   string // "o" or "c"
	comment string
}

func main() {
	fmt.Println("Downloading Unicode BidiBrackets property file...")

	entries, err := downloadAndParseBrackets(bracketsURL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing brackets file: %v\n", err)
		os.Exit(1)
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].r < entries[j].r
	})

	fmt.Printf("Parsed %d bracket entries\n", len(entries))

	if err := generateBracketsCode(entries); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating code: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Successfully generated brackets_data.go")
}

func downloadAndParseBrackets(url string) ([]bracketEntry, error) {
	resp, err := http.Get(url)
	if err != nil {
		return nil, fmt.Errorf("download: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("download: status %d", resp.StatusCode)
	}
	return parseBrackets(resp.Body)
}

func parseBrackets(r io.Reader) ([]bracketEntry, error) {
	var entries []bracketEntry
	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		raw := scanner.Text()
		// Capture the trailing comment for codegen documentation.
		var comment string
		if hash := strings.IndexByte(raw, '#'); hash >= 0 {
			comment = strings.TrimSpace(raw[hash+1:])
			raw = raw[:hash]
		}
		line := strings.TrimSpace(raw)
		if line == "" {
			continue
		}
		parts := strings.Split(line, ";")
		if len(parts) < 3 {
			continue
		}
		runeVal, err := strconv.ParseInt(strings.TrimSpace(parts[0]), 16, 32)
		if err != nil {
			continue
		}
		pairedVal, err := strconv.ParseInt(strings.TrimSpace(parts[1]), 16, 32)
		if err != nil {
			continue
		}
		ptype := strings.TrimSpace(parts[2])
		if ptype != "o" && ptype != "c" {
			log.Fatalf("unknown Bidi_Paired_Bracket_Type %q at U+%04X — update generator", ptype, runeVal)
		}
		entries = append(entries, bracketEntry{
			r:       rune(runeVal),
			paired:  rune(pairedVal),
			ptype:   ptype,
			comment: comment,
		})
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return entries, nil
}

func generateBracketsCode(entries []bracketEntry) error {
	out, err := os.Create("brackets_data.go")
	if err != nil {
		return err
	}
	defer out.Close()

	fmt.Fprintf(out, "// Code generated by generate_brackets.go. DO NOT EDIT.\n")
	fmt.Fprintf(out, "// Source: Unicode BidiBrackets-%s.txt\n", bracketsVersion)
	fmt.Fprintf(out, "\npackage uax9\n\n")
	fmt.Fprintf(out, "// bracketPairType encodes the Bidi_Paired_Bracket_Type property.\n")
	fmt.Fprintf(out, "// Reference: https://www.unicode.org/reports/tr9/#BD16\n")
	fmt.Fprintf(out, "type bracketPairType uint8\n\n")
	fmt.Fprintf(out, "const (\n")
	fmt.Fprintf(out, "\tbracketNone  bracketPairType = 0\n")
	fmt.Fprintf(out, "\tbracketOpen  bracketPairType = 1\n")
	fmt.Fprintf(out, "\tbracketClose bracketPairType = 2\n")
	fmt.Fprintf(out, ")\n\n")

	fmt.Fprintf(out, "// bracketEntry captures one row of BidiBrackets.txt.\n")
	fmt.Fprintf(out, "type bracketEntry struct {\n")
	fmt.Fprintf(out, "\tr      rune\n")
	fmt.Fprintf(out, "\tpaired rune\n")
	fmt.Fprintf(out, "\tptype  bracketPairType\n")
	fmt.Fprintf(out, "}\n\n")

	fmt.Fprintf(out, "// bracketData lists every code point with Bidi_Paired_Bracket_Type ∈ {Open, Close},\n")
	fmt.Fprintf(out, "// sorted ascending by code point for binary search.\n")
	fmt.Fprintf(out, "// Total entries: %d\n", len(entries))
	fmt.Fprintf(out, "var bracketData = []bracketEntry{\n")
	for _, e := range entries {
		var typeName string
		switch e.ptype {
		case "o":
			typeName = "bracketOpen"
		case "c":
			typeName = "bracketClose"
		}
		fmt.Fprintf(out, "\t{0x%04X, 0x%04X, %s}, // %s\n", e.r, e.paired, typeName, e.comment)
	}
	fmt.Fprintf(out, "}\n\n")

	fmt.Fprintf(out, "// getBracketInfo returns (type, paired-bracket) for the given rune.\n")
	fmt.Fprintf(out, "// For non-bracket characters, returns (bracketNone, 0).\n")
	fmt.Fprintf(out, "// Reference: https://www.unicode.org/reports/tr9/#BD16\n")
	fmt.Fprintf(out, "func getBracketInfo(r rune) (bracketPairType, rune) {\n")
	fmt.Fprintf(out, "\tlo, hi := 0, len(bracketData)-1\n")
	fmt.Fprintf(out, "\tfor lo <= hi {\n")
	fmt.Fprintf(out, "\t\tmid := (lo + hi) / 2\n")
	fmt.Fprintf(out, "\t\tentry := bracketData[mid]\n")
	fmt.Fprintf(out, "\t\tswitch {\n")
	fmt.Fprintf(out, "\t\tcase r < entry.r:\n")
	fmt.Fprintf(out, "\t\t\thi = mid - 1\n")
	fmt.Fprintf(out, "\t\tcase r > entry.r:\n")
	fmt.Fprintf(out, "\t\t\tlo = mid + 1\n")
	fmt.Fprintf(out, "\t\tdefault:\n")
	fmt.Fprintf(out, "\t\t\treturn entry.ptype, entry.paired\n")
	fmt.Fprintf(out, "\t\t}\n")
	fmt.Fprintf(out, "\t}\n")
	fmt.Fprintf(out, "\treturn bracketNone, 0\n")
	fmt.Fprintf(out, "}\n\n")

	// Canonical equivalence helper. U+2329 ≡ U+3008 and U+232A ≡ U+3009.
	// BD16 requires equivalent bracket characters be matched as if identical.
	fmt.Fprintf(out, "// canonicalBracket maps canonically-equivalent bracket characters\n")
	fmt.Fprintf(out, "// to a single representative so BD16 matching is correct.\n")
	fmt.Fprintf(out, "// U+2329 ≡ U+3008 and U+232A ≡ U+3009 per Unicode canonical equivalence.\n")
	fmt.Fprintf(out, "// Reference: https://www.unicode.org/reports/tr9/#BD16\n")
	fmt.Fprintf(out, "func canonicalBracket(r rune) rune {\n")
	fmt.Fprintf(out, "\tswitch r {\n")
	fmt.Fprintf(out, "\tcase 0x2329:\n")
	fmt.Fprintf(out, "\t\treturn 0x3008\n")
	fmt.Fprintf(out, "\tcase 0x232A:\n")
	fmt.Fprintf(out, "\t\treturn 0x3009\n")
	fmt.Fprintf(out, "\t}\n")
	fmt.Fprintf(out, "\treturn r\n")
	fmt.Fprintf(out, "}\n")

	return nil
}
